pipeline {
    agent
    tools {
       maven "Maven 3.6.1"
    } 
    stages{
        stage("one"){
            steps{
                echo 'Building worker app'
                dir ("worker") {
			sh 'mvn compile'
		}
            }
        }
        stage("two"){
            steps{
                echo 'step 2'
            }
        }
        stage("three"){
            steps{
                echo 'step 3'
            }
        }
    }
    post{
        always{
            echo 'This pipeline is completed..'
        }
    }
}
